variable "instance-type" {}
#variable "ami_id" {}
variable "sg-id" {}
variable "subnet-id" {}
variable "environment" {}
variable "key-name" {}
#variable "user-data" {}
variable "associate_public_ip_address" {}
variable "resource-attached"  {}